name: Build and Deploy
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types: [created]
jobs:
  build_and_deploy:
    name: build_and_deploy
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: read
      contents: read
      id-token: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Test ENV
        id: test-env
        env:
          TEST_ENV: "${{ secrets.TEST_ENV }}"
        run: echo ">>>>>>>>>> ${TEST_ENV}"
